// action types
export const FETCHING_REPOS_REQUEST = 'FETCHING_REPOS_REQUEST';
export const FETCHING_REPOS_SUCCESS = 'FETCHING_REPOS_SUCCESS';
export const FETCHING_REPOS_FAILED = 'FETCHING_REPOS_FAILED';

export const SAVING_REPOS_REQUEST = 'SAVING_REPOS_REQUEST';
export const SAVING_REPOS_SUCCESS = 'SAVING_REPOS_SUCCESS';
export const SAVING_REPOS_FAILED = 'SAVING_REPOS_FAILED';

export const CLEAR_ALL = 'CLEAR_ALL';
